name: DLL Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
        - uses: actions/checkout@v4
        - name: Setup .NET
            uses: actions/setup-dotnet@v4
        with:
            dotnet-version: 8.0.x
        - name: Restore dependencies
            run: dotnet restore src/Nyctophobia.sln /p:Configuration=Debug /p:Platform="Any CPU"
        - name: Build
            run: dotnet build src/Nyctophobia.sln --no-restore /p:Configuration=Debug /p:Platform="Any CPU"
        - name: Test
            run: dotnet test src/Nyctophobia.sln --no-build /p:Configuration=Debug /p:Platform="Any CPU"